const $=s=>document.querySelector(s);let videoFile=null,segments=[],selected=null,characters=[{id:"kairo",name:"Kairo",voice:"Commercial TTS — profile KAIRO-01",locked:true},{id:"aira",name:"Aira",voice:"Commercial TTS — profile AIRA-01",locked:true}],version=1;
const videoInput=$("#videoInput"),preview=$("#preview"),info=$("#videoInfo"),drop=$("#dropzone"),script=$("#script"),analyze=$("#analyzeBtn"),generate=$("#generateBtn");
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}
function fmt(n){n=Number(n)||0;return String(Math.floor(n/60)).padStart(2,"0")+":"+String(Math.floor(n%60)).padStart(2,"0")}
function bytes(n){const u=["B","KB","MB","GB"];let i=0;while(n>1024&&i<3){n/=1024;i++}return n.toFixed(i?1:0)+" "+u[i]}
function handleVideo(f){if(!f)return;if(!f.type.startsWith("video/"))return alert("Choose a video file.");videoFile=f;preview.src=URL.createObjectURL(f);preview.classList.remove("hidden");info.classList.remove("hidden");info.innerHTML="<b>"+esc(f.name)+"</b><small>"+bytes(f.size)+" • "+esc(f.type)+"</small>"}
videoInput.addEventListener("change",e=>handleVideo(e.target.files[0]));drop.addEventListener("drop",e=>{e.preventDefault();handleVideo(e.dataTransfer.files[0])});["dragover"].forEach(x=>drop.addEventListener(x,e=>e.preventDefault()));
function renderChars(){const box=$("#characters");box.innerHTML=characters.map(c=>"<div class='character'><div class='avatar'>"+esc(c.name[0])+"</div><div class='char-main'><b>"+esc(c.name)+"</b><small>"+esc(c.voice)+"</small></div><button class='lock "+(c.locked?"on":"")+"' data-lock='"+c.id+"'>"+(c.locked?"🔒 Locked":"🔓 Unlock")+"</button><button class='tiny' data-edit='"+c.id+"'>Edit</button></div>").join("");box.querySelectorAll("[data-lock]").forEach(b=>b.onclick=()=>{const c=characters.find(x=>x.id===b.dataset.lock);c.locked=!c.locked;renderChars()});box.querySelectorAll("[data-edit]").forEach(b=>b.onclick=()=>{const c=characters.find(x=>x.id===b.dataset.edit);const n=prompt("Character name",c.name);if(n)c.name=n;const v=prompt("Voice profile/provider label",c.voice);if(v)c.voice=v;renderChars()})}
renderChars();$("#addCharacter").onclick=()=>{const n=prompt("Character name");if(n){characters.push({id:crypto.randomUUID(),name:n,voice:"Commercial TTS — new profile",locked:true});renderChars()}};
function parse(){const lines=script.value.split(/\n/).map(x=>x.trim()).filter(Boolean);let t=0,out=[];for(const line of lines){if(/^SCENE\s*\d+/i.test(line)){continue}const m=line.match(/^([A-Za-z][A-Za-z0-9 _-]{1,30}):\s*(.+)$/);if(m){const c=characters.find(x=>x.name.toLowerCase()===m[1].toLowerCase());const dur=Math.max(2,Math.min(8,m[2].length/12));out.push({id:crypto.randomUUID(),type:"dialogue",name:m[1],text:m[2],start:t,end:t+dur,volume:1,characterId:c?.id||null,status:"active"});t+=dur}else{t+=1}}if(!out.length)out=[{id:crypto.randomUUID(),type:"music",name:"Ambient bed",text:"Original/licensed background music",start:0,end:Math.max(10,preview.duration||30),volume:.35,status:"active"}];return out}
analyze.onclick=()=>{if(!script.value.trim())return alert("Add your script first.");segments=parse();renderTimeline();generate.disabled=false};
async function callBackend(action,payload={}){const base=window.ANO_ANIME_API_URL;if(!base)return {ok:false,code:"BACKEND_NOT_CONFIGURED"};try{const r=await fetch(base,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,...payload})});return await r.json()}catch(e){return {ok:false,code:"NETWORK_ERROR",message:e.message}}}generate.onclick=async()=>{generate.disabled=true;generate.textContent="Generating…";if(!segments.length)segments=parse();const dialogues=segments.filter(s=>s.type==="dialogue");let result={ok:true};for(const s of dialogues){const ch=characters.find(c=>c.id===s.characterId);if(!ch)continue;result=await callBackend("voice",{text:s.text,voice_id:ch.voice,settings:{character:ch.name}});if(!result.ok)break}if(result.ok){segments=segments.concat([{id:crypto.randomUUID(),type:"sfx",name:"Scene ambience",text:"Licensed/user-owned ambience",start:0,end:Math.max(5,Math.min(20,preview.duration||20)),volume:.6,status:"active"},{id:crypto.randomUUID(),type:"music",name:"Background score",text:"Licensed/user-owned music",start:0,end:Math.max(10,preview.duration||30),volume:.3,status:"active"}]);renderTimeline();$("#renderStatus").textContent="Audio generation completed/queued for the selected voice provider."}else{$("#renderStatus").textContent=result.code==="BACKEND_NOT_CONFIGURED"?"Audio backend is not connected yet. Configure the secure TTS provider in Supabase.":(result.message||"Audio generation failed.")}generate.disabled=false;generate.textContent="Generate audio";};
function renderTimeline(){const box=$("#timeline");if(!segments.length){box.className="timeline empty";box.textContent="Analyze your episode to create the editable timeline.";return}box.className="timeline";box.innerHTML=segments.map((s,i)=>"<button class='segment "+s.type+" "+(s.status==="muted"?"mutedSeg ":"")+(selected?.id===s.id?"selected":"")+"' data-id='"+s.id+"'><span>"+esc(s.type.toUpperCase())+"</span><b>"+esc(s.name)+"</b><small>"+fmt(s.start)+" → "+fmt(s.end)+"</small><em>"+(s.status==="muted"?"MUTED":"")+" </em></button>").join("");box.querySelectorAll(".segment").forEach(b=>b.onclick=()=>selectSegment(b.dataset.id))}
function selectSegment(id){selected=segments.find(s=>s.id===id);if(!selected)return;$("#editorEmpty").classList.add("hidden");$("#editor").classList.remove("hidden");$("#selectedType").textContent=selected.type.toUpperCase();$("#selectedName").textContent=selected.name;$("#segmentText").value=selected.text||"";$("#start").value=selected.start;$("#end").value=selected.end;$("#volume").value=selected.volume??1;$("#revisionNote").textContent="Changes create a new segment revision; the original version remains recoverable." ;renderTimeline()}
$("#saveSegment").onclick=()=>{if(!selected)return;selected.text=$("#segmentText").value;selected.start=Number($("#start").value)||0;selected.end=Number($("#end").value)||selected.start+1;selected.volume=Number($("#volume").value);selected.status="active";version++;$("#version").textContent=version;renderTimeline();$("#revisionNote").textContent="Saved as revision "+version+" — other segments were not changed."}
$("#regenerate").onclick=()=>{if(!selected)return;selected.status="regenerating";renderTimeline();setTimeout(()=>{selected.status="active";$("#revisionNote").textContent="Regeneration requested for this segment only. The final backend will call the selected licensed provider.";renderTimeline()},500)}
$("#mute").onclick=()=>{if(!selected)return;selected.status=selected.status==="muted"?"active":"muted";renderTimeline()}
$("#remove").onclick=()=>{if(!selected)return;if(confirm("Remove only this segment?")){segments=segments.filter(x=>x.id!==selected.id);selected=null;$("#editor").classList.add("hidden");$("#editorEmpty").classList.remove("hidden");renderTimeline()}}
$("#previewSegment").onclick=()=>{if(!selected)return;preview.currentTime=Math.max(0,selected.start);preview.play();setTimeout(()=>preview.pause(),Math.max(500,(selected.end-selected.start)*1000))}
$("#render").onclick=()=>{$("#renderStatus").textContent="Render queued. The production backend will mix dialogue, SFX and music and export MP4.";addVersion("Render queued")}
$("#duplicate").onclick=()=>{version++;$("#version").textContent=version;addVersion("Draft copy")}
function addVersion(status){const d=document.createElement("div");d.textContent="Version "+version+" • "+status;$("#versions").prepend(d)}
$("#playTimeline").onclick=()=>{if(preview.paused)preview.play();else preview.pause()};preview.addEventListener("timeupdate",()=>{$("#currentTime").textContent=fmt(preview.currentTime);$("#playhead").style.width=(preview.duration?preview.currentTime/preview.duration*100:0)+"%";$("#totalTime").textContent=fmt(preview.duration)});
$("#newEpisode").onclick=()=>{if(confirm("Start a new episode? Current local timeline will be cleared.")){segments=[];selected=null;script.value="";preview.classList.add("hidden");info.classList.add("hidden");renderTimeline()}}

window.ANO_ANIME_API_URL=window.ANO_ANIME_API_URL||"";
